version: "3.8"
services:
  auth-ms:
    container_name: auth-ms
    image: auth-ms
    build: .
    ports:
      - "8081:8081"
    # depends_on:
    #   - auth-ms-db
    environment:
      - SERVER_URL=${AUTH_MS_SERVER_URL}
      - AUTH_MS_DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - AUTH_MS_DATABASE_USERNAME=${AUTH_MS_DATABASE_USERNAME}
      - AUTH_MS_DATABASE_PASSWORD=${AUTH_MS_DATABASE_PASSWORD}
      - AUTH_MS_DATABASE_NAME=${AUTH_MS_DATABASE_NAME}
      - AUTH_MS_DATABASE_DIALECT=postgres
      - AUTH_MS_DATABASE_HOST=auth-ms-db
      - AUTH_MS_DATABASE_PORT=5432
volumes:
  db:
    driver: local
